package domain

import io.circe.generic.semiauto.{deriveDecoder, deriveEncoder}
import io.circe.{Decoder, DecodingFailure, Encoder, Json}

import java.time.Instant
import java.util.UUID

/** Sealed ADT representing all domain events that can occur on an account.
 *
 * All events share a common identity — `accountId`, `eventId`, and `occurredAt` —
 * generated by the HTTP service at the time of the transaction.
 */
sealed trait AccountEvent {
  def accountId: String
  def eventId: UUID
  def occurredAt: Instant
}

object AccountEvent {

  /** Emitted when a new account is opened with an initial balance. */
  final case class AccountCreated(
                                   accountId: String,
                                   eventId: UUID,
                                   occurredAt: Instant,
                                   initialBalance: BigDecimal
                                 ) extends AccountEvent

  /** Emitted when funds are withdrawn from an account. */
  final case class AccountDebited(
                                   accountId: String,
                                   eventId: UUID,
                                   occurredAt: Instant,
                                   amount: BigDecimal,
                                   newBalance: BigDecimal
                                 ) extends AccountEvent

  /** Emitted when funds are deposited into an account. */
  final case class AccountCredited(
                                    accountId: String,
                                    eventId: UUID,
                                    occurredAt: Instant,
                                    amount: BigDecimal,
                                    newBalance: BigDecimal
                                  ) extends AccountEvent

  // Subtype encoders and decoders — derived automatically via circe-generic
  implicit val createdEncoder: Encoder[AccountCreated]    = deriveEncoder
  implicit val debitedEncoder: Encoder[AccountDebited]    = deriveEncoder
  implicit val creditedEncoder: Encoder[AccountCredited]  = deriveEncoder

  implicit val createdDecoder: Decoder[AccountCreated]    = deriveDecoder
  implicit val debitedDecoder: Decoder[AccountDebited]    = deriveDecoder
  implicit val creditedDecoder: Decoder[AccountCredited]  = deriveDecoder

  /** Encodes any AccountEvent as flat JSON with an explicit `eventType` discriminator field.
   *
   * Example output:
   * {{{
   * {
   *   "eventType": "AccountDebited",
   *   "accountId": "acc-1",
   *   "eventId": "...",
   *   "occurredAt": "...",
   *   "amount": 50,
   *   "newBalance": 150
   * }
   * }}}
   */
  implicit val accountEventEncoder: Encoder[AccountEvent] = Encoder.instance {
    case e: AccountCreated  => createdEncoder(e).deepMerge(Json.obj("eventType" -> Json.fromString("AccountCreated")))
    case e: AccountDebited  => debitedEncoder(e).deepMerge(Json.obj("eventType" -> Json.fromString("AccountDebited")))
    case e: AccountCredited => creditedEncoder(e).deepMerge(Json.obj("eventType" -> Json.fromString("AccountCredited")))
  }

  /** Decodes a flat JSON payload into the correct AccountEvent subtype using the `eventType` field.
   * Unknown event types are rejected with a DecodingFailure — malformed events are routed to DLQ.
   */
  implicit val accountEventDecoder: Decoder[AccountEvent] = Decoder.instance { cursor =>
    cursor.get[String]("eventType").flatMap {
      case "AccountCreated"  => createdDecoder.tryDecode(cursor)
      case "AccountDebited"  => debitedDecoder.tryDecode(cursor)
      case "AccountCredited" => creditedDecoder.tryDecode(cursor)
      case other             => Left(DecodingFailure(s"Unknown eventType: $other", cursor.history))
    }
  }
}